### ISSUE TITLE
Priority of snippets (luasnip)

### ISSUE THREAD

**Issue by GordianDziwis** [zjp-CN/nvim-cmp-lsp-rs#5]
When starting with an empty line, giving snippets a higher priority than structs could be useful.

![image](https://github.com/zjp-CN/nvim-cmp-lsp-rs/assets/3330855/627c1066-afbb-4a0f-98d1-c7dea5cee756)

**Comment by zjp-CN** [comment]
Good idea. So there are at least two ways to do that:
* add a comparator that looks into the cursor context, like the current line is empty, then prioritize some snippet kinds. 
* Or use `exact + score` comparators built in nvim-cmp, to make `while` first by ignoring entry kinds. ([example](https://github.com/zjp-CN/nvim-cmp-lsp-rs/issues/4#issuecomment-2041308464)) This brings some other benefits that good matching chars are prior to entry kinds as you see in the link.

**Comment by GordianDziwis** [comment]
A thanks, I used `offset + score` and this is better. I kinda wonder why this is not solved by cmp? The difference between vanilla cmp and cmp with your plugin is one of day and night. And is anywhere documented what those comparators actually do?

**Comment by zjp-CN** [comment]
You can check out the background part collapsed in README in this repo, and read the comments in the [source code in nvim-cmp](https://github.com/hrsh7th/nvim-cmp/blob/97dc716fc914c46577a4f254035ebef1aa72558a/lua/cmp/config/compare.lua)  to know functionalities of these comparators there.
